export enum GatewayCapability {
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  VERIFY = 'VERIFY',
  INQUIRY = 'INQUIRY',
  REFUND = 'REFUND',
  REVERSE = 'REVERSE',
  CALLBACK = 'CALLBACK',
  WEBHOOK = 'WEBHOOK',
  TOKENIZATION = 'TOKENIZATION',
  RECURRING = 'RECURRING',
}
