export enum GatewayCapability {
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  AUTHORIZE = 'AUTHORIZE',
  CAPTURE = 'CAPTURE',
  CANCEL = 'CANCEL',
  VERIFY = 'VERIFY',
  INQUIRY = 'INQUIRY',
  REFUND = 'REFUND',
  REVERSE = 'REVERSE',
  CALLBACK = 'CALLBACK',
  WEBHOOK = 'WEBHOOK',
  TOKENIZATION = 'TOKENIZATION',
  RECURRING = 'RECURRING',
}
